### ISSUE TITLE
"Some error occured here"

### ISSUE THREAD

**Issue by gbell12** [chrisbra/Colorizer#42]
Getting this on ColorToggle stable:

Colorizer: Some error occured here:  Colorize: ['#\%(\x\{3}\|\x\{6}\)\%(\>\|[-_]\)\@=', function('<SNR>66_
PreviewColorHex'), 'colorizer_hex', 1]  

Not sure what else to provide.  Vim 7.4.52.  Doesn't happen on a blank file.  Happens with a file with only #350344 in it.

**Comment by chrisbra** [comment]
Am 2015-02-25 11:21, schrieb gbell12:
> Getting this on ColorToggle:
> 
> Colorizer: Some error occured here: Colorize:
> ['#%(x{3}|x{6})%(>|[-_])@=', function('66_
>  PreviewColorHex'), 'colorizer_hex', 1]
> 
> Not sure what else to provide. Vim 7.4.52. Doesn't happen on a blank
> file. Happens with a file with only #350344 in it.

Interesting. Can you provide the file?

Thanks.

Best,
Christian

**Comment by gbell12** [comment]
Put #350344 in any file.

Git head is saying this:

Error detected while processing function Colorizer#ColorToggle..Colorizer#DoColor..Colorizer#ColorOff:
line    7:
E28: No such highlight group name: ColorTermESC
Colorizer: Some error occured here:  Colorize: ['#\%(\x\{3}\|\x\{6}\)\%(\>\|[-_]\)\@=', function('<SNR>61_PreviewColorHex'), 'colorizer_
hex', 1, []]
Error detected while processing function Colorizer#ColorToggle..Colorizer#DoColor:
line  142:
E121: Undefined variable: s:position
E116: Invalid arguments for function string(s:position))
E116: Invalid arguments for function <SNR>61_Warn
line  143:
E121: Undefined variable: s:position
E116: Invalid arguments for function matchadd
Press ENTER or type command to continue

**Comment by gbell12** [comment]
Ah, and this is with no .vim or .vimrc either... so clean run.

**Comment by chrisbra** [comment]
Am 2015-02-25 11:24, schrieb gbell12:
> Put #350344 in any file.

I do not see that.

> 
> Git head is saying this:
> 
> Error detected while processing function
> Colorizer#ColorToggle..Colorizer#DoColor..Colorizer#ColorOff:
>  line 7:
>  E28: No such highlight group name: ColorTermESC

That should have been fixed by commit 75476dc and a2ec7059

Can you please update to the latest version?

>  Colorizer: Some error occured here: Colorize:
> ['#%(x{3}|x{6})%(>|[-_])@=', function('61_PreviewColorHex'),
> 'colorizer_
>  hex', 1, []]
>  Error detected while processing function
> Colorizer#ColorToggle..Colorizer#DoColor:
>  line 142:
>  E121: Undefined variable: s:position

That is a problem. I'll fix that.

Best,
Christian

**Comment by chrisbra** [comment]
I have updated the plugin. Does it still happen?

**Comment by gbell12** [comment]
Git clone and vim Colorizer.vmb and :so %.  That should be enough to install on top?

Still getting:

Colorizer: Some error occured here:  Colorize: ['#\%(\x\{3}\|\x\{6}\)\%(\>\|[-_]\)\@=', function('<SNR>63_PreviewColorHex'), 'colorizer_
hex', 1, []]

**Comment by chrisbra** [comment]
Hi gbell12!

On Mi, 25 Feb 2015, gbell12 wrote:

> Git clone and vim Colorizer.vmb and :so %.  That should be enough to install on top?
> 
> Still getting:
> 
> Colorizer: Some error occured here:  Colorize: ['#\%(\x\{3}\|\x\{6}\)\%(\>\|[-_]\)\@=', function('<SNR>63_PreviewColorHex'), 'colorizer_
> hex', 1, []]

Ah, it's actually your Vim version, that is too old. There was a typo 
when checking for the correct patch, so therefore you saw that error. I 
fixed it now.

Best,
Christian
-- 
Wenn etwas sicher ist, dann ist es nur die Unsicherheit.
		-- Beatrix (Königin der Niederlande, Thronrede)
